import {withTenantContext} from '../infrastructure/database-context.js';import {AppError} from '../middleware/errors.js';import {encryptCredential} from '../security/credential-crypto.js';
async function ensureAgent(client,tenantId,agentId){const r=await client.query('SELECT usage_direction FROM voice_agents WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL',[tenantId,agentId]);if(!r.rowCount)throw new AppError(404,'Voice agent was not found','AGENT_NOT_FOUND');return r.rows[0];}
function tool(row){return{id:row.id,agentId:row.agent_id,name:row.name,type:row.type,description:row.description,status:row.status,configuration:row.configuration,hasSecretConfiguration:Boolean(row.secret_configuration_encrypted),createdAt:row.created_at,updatedAt:row.updated_at};}
function doc(row){return{id:row.id,agentId:row.agent_id,displayName:row.display_name,fileName:row.file_name,mimeType:row.mime_type,sizeBytes:Number(row.size_bytes),storageBackend:row.storage_backend,objectKey:row.object_key,checksumSha256:row.checksum_sha256,ingestionStatus:row.ingestion_status,ingestionError:row.ingestion_error,metadata:row.metadata,createdAt:row.created_at,updatedAt:row.updated_at};}
export function listTools(auth,agentId){return withTenantContext(auth,async c=>{await ensureAgent(c,auth.tenantId,agentId);const r=await c.query('SELECT * FROM agent_tools WHERE tenant_id=$1 AND agent_id=$2 AND deleted_at IS NULL ORDER BY created_at',[auth.tenantId,agentId]);return r.rows.map(tool);});}
export function createTool(auth,agentId,input){return withTenantContext(auth,async c=>{await ensureAgent(c,auth.tenantId,agentId);try{const r=await c.query(`INSERT INTO agent_tools(tenant_id,workspace_id,agent_id,name,type,description,status,configuration,secret_configuration_encrypted,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10)RETURNING *`,[auth.tenantId,auth.workspaceId,agentId,input.name,input.type,input.description??null,input.status,JSON.stringify(input.configuration),input.secretConfiguration?encryptCredential(JSON.stringify(input.secretConfiguration)):null,auth.userId]);return tool(r.rows[0]);}catch(e){if(e.code==='23505')throw new AppError(409,'Tool name already exists for this agent','AGENT_TOOL_EXISTS');throw e;}});}
export function updateToolStatus(auth,agentId,id,status){return withTenantContext(auth,async c=>{await ensureAgent(c,auth.tenantId,agentId);const r=await c.query('UPDATE agent_tools SET status=$4 WHERE tenant_id=$1 AND agent_id=$2 AND id=$3 AND deleted_at IS NULL RETURNING *',[auth.tenantId,agentId,id,status]);if(!r.rowCount)throw new AppError(404,'Agent tool was not found','AGENT_TOOL_NOT_FOUND');return tool(r.rows[0]);});}
export function updateTool(auth,agentId,id,input){return withTenantContext(auth,async c=>{await ensureAgent(c,auth.tenantId,agentId);const assignments=[];const values=[auth.tenantId,agentId,id];const add=(column,value,cast='')=>{values.push(value);assignments.push(`${column}=$${values.length}${cast}`);};if(Object.hasOwn(input,'name'))add('name',input.name);if(Object.hasOwn(input,'type'))add('type',input.type,'::agent_tool_type');if(Object.hasOwn(input,'description'))add('description',input.description);if(Object.hasOwn(input,'status'))add('status',input.status,'::agent_resource_status');if(Object.hasOwn(input,'configuration'))add('configuration',JSON.stringify(input.configuration),'::jsonb');if(Object.hasOwn(input,'secretConfiguration'))add('secret_configuration_encrypted',encryptCredential(JSON.stringify(input.secretConfiguration)));try{const r=await c.query(`UPDATE agent_tools SET ${assignments.join(',')} WHERE tenant_id=$1 AND agent_id=$2 AND id=$3 AND deleted_at IS NULL RETURNING *`,values);if(!r.rowCount)throw new AppError(404,'Agent tool was not found','AGENT_TOOL_NOT_FOUND');return tool(r.rows[0]);}catch(e){if(e.code==='23505')throw new AppError(409,'Tool name already exists for this agent','AGENT_TOOL_EXISTS');throw e;}});}
export function deleteTool(auth,agentId,id){return withTenantContext(auth,async c=>{const r=await c.query('UPDATE agent_tools SET deleted_at=now(),status=\'inactive\' WHERE tenant_id=$1 AND agent_id=$2 AND id=$3 AND deleted_at IS NULL RETURNING id',[auth.tenantId,agentId,id]);if(!r.rowCount)throw new AppError(404,'Agent tool was not found','AGENT_TOOL_NOT_FOUND');return{id,deleted:true};});}
export function listDocuments(auth,agentId){return withTenantContext(auth,async c=>{await ensureAgent(c,auth.tenantId,agentId);const r=await c.query('SELECT * FROM agent_knowledge_documents WHERE tenant_id=$1 AND agent_id=$2 AND deleted_at IS NULL ORDER BY created_at DESC',[auth.tenantId,agentId]);return r.rows.map(doc);});}
export function createDocument(auth,agentId,input){return withTenantContext(auth,async c=>{const agent=await ensureAgent(c,auth.tenantId,agentId);const metadata={...input.metadata,usageDirection:agent.usage_direction};const r=await c.query(`INSERT INTO agent_knowledge_documents(tenant_id,workspace_id,agent_id,display_name,file_name,mime_type,size_bytes,metadata,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9)RETURNING *`,[auth.tenantId,auth.workspaceId,agentId,input.displayName,input.fileName,input.mimeType,input.sizeBytes,JSON.stringify(metadata),auth.userId]);return doc(r.rows[0]);});}
export function completeDocumentUpload(auth,agentId,id,input){return withTenantContext(auth,async c=>{await ensureAgent(c,auth.tenantId,agentId);try{const r=await c.query(`UPDATE agent_knowledge_documents SET object_key=$4,checksum_sha256=$5,ingestion_status='uploaded',ingestion_error=NULL WHERE tenant_id=$1 AND agent_id=$2 AND id=$3 AND deleted_at IS NULL RETURNING *`,[auth.tenantId,agentId,id,input.objectKey,input.checksumSha256]);if(!r.rowCount)throw new AppError(404,'Knowledge document was not found','KNOWLEDGE_DOCUMENT_NOT_FOUND');return doc(r.rows[0]);}catch(e){if(e.code==='23505')throw new AppError(409,'This B2 object is already registered','KNOWLEDGE_OBJECT_EXISTS');throw e;}});}
export function deleteDocument(auth,agentId,id){return withTenantContext(auth,async c=>{const r=await c.query('UPDATE agent_knowledge_documents SET deleted_at=now() WHERE tenant_id=$1 AND agent_id=$2 AND id=$3 AND deleted_at IS NULL RETURNING id',[auth.tenantId,agentId,id]);if(!r.rowCount)throw new AppError(404,'Knowledge document was not found','KNOWLEDGE_DOCUMENT_NOT_FOUND');return{id,deleted:true};});}
